platform :ios, '8.0'

target 'MT_Guoke' do
pod 'FMDB'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MMProgressHUD'
pod 'SDWebImage'
pod 'CHTCollectionViewWaterfallLayout'
pod 'YYModel'
pod 'AFNetworking'
pod 'Masonry'
pod 'ViewDeck'
pod ‘SVProgressHUD’

end